export default {
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    GET_VACATIONS: "GET_VACATIONS",
    INIT: "INIT",
    ADD_VACATION: "ADD_VACATION",
    DELETE_VACATION: "DELETE_VACATION",
    EDIT_VACATION: "EDIT_VACATION"
}